general_settings:
  recordlengths: 2000 #noise 12500, normal 2000
  pretriggers: 500 # samples [0, 2042]
  software_trigger_rate: 100 # Hz
  max_file_size_mb: 100
  buffer_size: 500
  interval_stats: 2000
  iolevel: TTL
  acqtriggersource: ITLB #TrgIn #ITLB #
  busyinsource: SIN
  entriggeroverlap: False
  itlaenretrigger: False
  itlagatewidth: 0
  itlamainlogic: AND
  itlamajoritylev: 1
  itlamask: 0x003
  itlapairlogic: NONE
  itlapolarity: Direct
  startsource: SWcmd
channel_settings:
  group1:
    channels: "0..3"
    chenable: False
    chsupprsamplesoverthreshold: 1
    chsupprthr: 0
    dcoffset: 10
    itlconnect: ITLA
    overthresholdvetowidth: 0
    samplesoverthreshold: 1
    selftriggeredge: RISE
    selftriggerwidth: 2
    signaloffset: 0
    triggerthr: 200
    triggerthrmode: Relative
  group2:
    channels: "16"
    chenable: True
    chsupprsamplesoverthreshold: 1
    chsupprthr: 0
    dcoffset: 80
    itlconnect: ITLB
    overthresholdvetowidth: 0
    samplesoverthreshold: 1
    selftriggeredge: FALL
    selftriggerwidth: 2
    signaloffset: 0
    triggerthr: -800
    triggerthrmode: Relative
